# --- Configuraci�n del DataSource personalizado ---
spring.datasource.driver.class=org.postgresql.Driver
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASS}
spring.jpa.hibernate.ddl-auto=none
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.open-in-view=false

# Flyway
spring.flyway.enabled=false

flyway.erp.locations=classpath:db/migration
flyway.erp.history-table=flyway_schema_history
flyway.erp.schema-name=public
flyway.erp.enabled=true

spring.cloud.config.enabled=false
spring.cloud.config.import-check.enabled=false

# (Opcional) logging
logging.level.root=INFO
logging.level.com.tu.paquete=DEBUG
# Informaci�n general del API
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.enabled=true
server.port=${PORT:8081}
# URL base del servidor (localhost)
openapi.url.dev=http://localhost:8081
openapi.description.dev=Local Development Server



